[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[workspace]
members = ["programs/cp-swap"]

[features]
seeds = false
skip-lint = false

[programs.localnet]
kedolik_cp_swap = "Hr4iqmE5wiStSiHGgzgUSryNG4hyqkSHUT7PDyAsE6Li"

[programs.devnet]
kedolik_cp_swap = "Hr4iqmE5wiStSiHGgzgUSryNG4hyqkSHUT7PDyAsE6Li"

[programs.mainnet]
kedolik_cp_swap = "Hr4iqmE5wiStSiHGgzgUSryNG4hyqkSHUT7PDyAsE6Li"

[registry]
url = "https://github.com/kedolik-io/kedolik-cp-swap"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/mainnet-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/fee_receiver_unified.test.ts tests/one_hop_pricing.test.ts tests/deposit.test.ts tests/dust_reserve_fix.test.ts tests/initialize.test.ts tests/real_pyth_example_clean.test.ts tests/swap.test.ts tests/withdraw.test.ts"

[test]
startup_wait = 20000

[test.validator]
url = "https://api.mainnet-beta.solana.com"
